# Generated by Django 5.2.1 on 2026-06-28 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='item',
        ),
        migrations.RemoveField(
            model_name='links',
            name='user',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='todo',
            field=models.ForeignKey(blank=True, help_text='Tarefa associada | não é obrigatório', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='main.todo'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Item da lista', max_length=255)),
                ('feito', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('black', 'Preto'), ('white', 'Branco')], default='black', max_length=20)),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklist.tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='checklist.tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
