# Generated by Django 5.2.1 on 2026-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_remove_links_item_remove_links_user_tarefa_todo_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='feito',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('fazendo', 'Fazendo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20),
        ),
    ]
