# Generated by Django 5.2.1 on 2026-06-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_item_feito'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
