# Generated by Django 5.2.1 on 2026-05-01 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0013_alter_todo_prazo_final_alter_todo_prazo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='anotacao',
            field=models.TextField(default='Escreva algo aqui!', max_length=15000, verbose_name='Anotação'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-05-01'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-05-01'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', '1'), ('Média', '2'), ('Alta', '3')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Atividade', 'Atividade'), ('Prova', 'prova'), ('Arquivo', 'Arquivo'), ('Urgente', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa', 'Tarefa'), ('Link', 'Link'), ('Lembrete.', 'Lembrete'), ('Avulso', 'Avulso'), ('Outro', 'Outro')], default=('Avulso', 'Avulso'), max_length=13),
        ),
    ]
