# Generated by Django 5.2.1 on 2026-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0014_alter_todo_anotacao_alter_todo_prazo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='anotacao',
            field=models.TextField(default='Escreva algo aqui!', verbose_name='Anotação'),
        ),
    ]
