# Generated by Django 5.2.1 on 2026-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0015_alter_todo_anotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Atividade', 'Atividade'), ('Anotação', 'Anotação'), ('Prova', 'prova'), ('Arquivo', 'Arquivo'), ('Urgente', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa', 'Tarefa'), ('Link', 'Link'), ('Lembrete.', 'Lembrete'), ('Avulso', 'Avulso'), ('Outro', 'Outro')], default=('Avulso', 'Avulso'), max_length=13),
        ),
    ]
