# Generated by Django 5.2.1 on 2026-06-21 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0016_alter_todo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-06-21'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-06-21'),
        ),
    ]
