# Generated by Django 5.2.1 on 2026-06-27 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='folder', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem titulo', max_length=200)),
                ('favorito', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('anotacao', models.TextField(default='Escreva algo aqui!', verbose_name='Anotação')),
                ('prioridade', models.CharField(choices=[('Baixa', '1'), ('Média', '2'), ('Alta', '3')], default='1', max_length=10)),
                ('tag', models.CharField(choices=[('Atividade', 'Atividade'), ('Anotação', 'Anotação'), ('Prova', 'prova'), ('Arquivo', 'Arquivo'), ('Urgente', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa', 'Tarefa'), ('Link', 'Link'), ('Lembrete.', 'Lembrete'), ('Avulso', 'Avulso'), ('Outro', 'Outro')], default=('Avulso', 'Avulso'), max_length=13)),
                ('prazo_inicial', models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-06-27')),
                ('prazo_final', models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-06-27')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='init.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('descricao', models.CharField(default='Imagem sem descriçao', max_length=1000)),
                ('titulo', models.CharField(default='Sem titulo', max_length=1000)),
                ('data_de_criacao', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(default='Sem observação', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='init.todo')),
            ],
        ),
    ]
