# Generated by Django 5.2.1 on 2026-09-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='tipo_de_evento',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Atividade', 'Atividade'), ('Terefa', 'Tarefa'), ('Importante', 'Importante'), ('Lembrete', 'Lembrete'), ('Outro', 'Outro')], default=('Lembrete', 'Lembrete'), max_length=100, verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(blank=True, default='Sem descrição', max_length=100, verbose_name='Descrição')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamodel', verbose_name='Registro da agenda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
