# Generated by Django 5.2.1 on 2026-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agendamodel_tipo_de_evento_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='importancia',
            field=models.CharField(choices=[('1', 'Mínima'), ('2', 'Mediana'), ('3', 'Máxima')], default=('1', 'Mínima'), max_length=100, verbose_name='Importância'),
        ),
    ]
