# Generated by Django 5.2.1 on 2026-07-05 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='folder',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='pastas_compartilhadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='main.todo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='todos_compartilhados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_pastas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='main.folder'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-07-05'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-07-05'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Atividade', 'Atividade'), ('Anotação', 'Anotação'), ('Prova', 'prova'), ('Arquivo', 'Arquivo'), ('Urgente', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa', 'Tarefa'), ('Link', 'Link'), ('Lembrete.', 'Lembrete'), ('Avulso', 'Avulso'), ('Outro', 'Outro')], default='Avulso', max_length=13),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
