# Generated by Django 5.2.1 on 2026-09-27 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='2026-09-27'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='2026-09-27'),
        ),
    ]
