# Generated by Django 5.2.1 on 2026-09-06 16:29

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=main.models._upload_imagem_path),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-09-06'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-09-06'),
        ),
    ]
