# Generated by Django 5.2.1 on 2026-09-11 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_image_img_alter_todo_prazo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-09-11'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-09-11'),
        ),
    ]
