# Generated by Django 5.2.1 on 2026-07-11 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_image_user_folder_colaboradores_image_todo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-07-11'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2026-07-11'),
        ),
        migrations.CreateModel(
            name='CollaborationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='grupos_que_participo', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_que_criei', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='grupos_colaboracao',
            field=models.ManyToManyField(blank=True, related_name='pastas_compartilhadas', to='main.collaborationgroup'),
        ),
        migrations.AddField(
            model_name='todo',
            name='grupos_colaboracao',
            field=models.ManyToManyField(blank=True, related_name='todos_compartilhados', to='main.collaborationgroup'),
        ),
    ]
