# Generated by Django 5.2.1 on 2026-09-27 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data_de_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='2026-09-27'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='2026-09-27'),
        ),
    ]
